export const skills = [
    "Software Engineer",
    "UI/UX Designer",
    "Fullstack Developer",
    "Frontend Developer",
    "Backend Developer",
    "DevOps Engineer",
    "Data Scientist",
    "Data Analyst",
    "Machine Learning Engineer",
    "Artificial Intelligence Specialist",
    "Cloud Engineer",
    "Cybersecurity Specialist",
    "Blockchain Developer",
    "Game Developer",
    "Mobile App Developer",
    "iOS Developer",
    "Android Developer",
    "Quality Assurance Engineer",
    "Automation Engineer",
    "Database Administrator",
    "Network Engineer",
    "Systems Architect",
    "Product Manager",
    "Project Manager",
    "Business Analyst",
    "Scrum Master",
    "Tech Support Specialist",
    "IT Consultant",
    "Technical Writer",
    "Graphic Designer",
    "Motion Graphics Designer",
    "3D Animator",
    "Augmented Reality Developer",
    "Virtual Reality Developer",
    "Software Tester",
    "API Developer",
    "Embedded Systems Engineer",
    "Electrical Engineer",
    "Mechanical Engineer",
    "Civil Engineer",
    "Robotics Engineer",
    "Industrial Designer",
    "SEO Specialist",
    "Content Manager",
    "Digital Marketing Specialist",
    "Social Media Manager",
    "Web Developer",
    "E-commerce Specialist",
    "Big Data Engineer",
    "Bioinformatics Specialist",
    "Video Editor",
    "Audio Engineer",
    "Ethical Hacker",
    "UI Developer",
    "IT Auditor",
    "Game Designer",
    "IT Administrator",
    "CRM Specialist",
    "ERP Specialist",
    "Software Architect",
    "Site Reliability Engineer (SRE)",
    "Penetration Tester",
    "Algorithm Developer",
    "Computer Vision Engineer",
    "NLP Specialist",
    "IT Trainer",
    "Technical Support Analyst",
    "Cloud Security Specialist",
    "Security Analyst",
    "Data Engineer",
    "Statistician",
    "Research Scientist",
    "DevSecOps Engineer",
    "Performance Engineer",
    "Release Manager",
    "Build Engineer",
    "System Administrator",
    "Help Desk Technician",
    "Tech Evangelist",
    "UX Researcher",
    "Digital Product Designer",
    "Frontend Architect",
    "Backend Architect",
    "Computer Engineer",
    "Cyber Forensics Specialist",
    "Graphics Programmer",
    "Audio Programmer",
    "Firmware Developer",
    "Virtualization Engineer",
    "AI Research Scientist",
    "Quantum Computing Engineer",
    "Software Trainer",
    "EdTech Specialist",
    "Creative Coder",
    "Operations Analyst",
    "Software Localization Specialist",
    "Interactive Designer",
    "Hardware Engineer",
    "Augmented Reality Designer",
    "Data Privacy Specialist",
    "Cloud Solutions Architect",
    "Wireless Communications Engineer",
    "Cryptocurrency Developer",
  ];
  